// Autogenerated by geninfo, do not edit

package gcewing.architecture;

public class Info {
	static final String modName = "ArchitectureCraft";
	static final String modID = "architecturecraft";
	//static final String modPackage = "";
	static final String versionNumber = "1.5.1";
	static final String versionBounds = "[1.5,1.6)";
	static final String acceptedMinecraftVersions = "[1.10.2,1.10.2]";
}
