// Autogenerated by geninfo, do not edit

package gcewing.architecture;

public class Info {
	static final String modName = "ArchitectureCraft";
	static final String modID = "ArchitectureCraft";
	//static final String modPackage = "";
	static final String versionNumber = "1.4.1";
	static final String versionBounds = "[1.4,1.5)";
	static final String acceptedMinecraftVersions = "[1.8.8,1.8.9]";
}
